approvedGitRepositories:
  - "**"

catalog:
  "@types/node": "npm:@types/node@26.6.4"
  vite: "npm:@voidzero-dev/vite-plus-core@1.1.0"
  vite-plus: 1.1.0
  vitest: "npm:vitest@4.1.11"

enableScripts: true

nodeLinker: node-modules

npmMinimalAgeGate: 0

npmScopes:
  jsr:
    npmRegistryServer: "https://npm.jsr.io"

yarnPath: .yarn/releases/yarn-4.18.1.cjs
