//! Real-weights paged-vs-flat numerical-equivalence gate for NemotronH.
//!
//! Only the `full_attention` layers route through the block-paged adapter;
//! mamba layers keep per-request recurrent state and moe layers are stateless.
//! T=0 parity proves the per-layer routing agrees with the flat path on the
//! attention layers without disturbing the mamba states on the others.
//!
//! Reads the GENERIC `MLX_TEST_MODEL_PATH`, while the sibling gates
//! `nemotron_h_concurrent_batched_parity.rs` and
//! `nemotron_h_mtp_midcycle_state.rs` read `MLX_TEST_NEMOTRON_H_MODEL_PATH` —
//! set both or some of them silently skip.

use std::fs;
use std::path::{Path, PathBuf};

use mlx_core::engine::types::{ChatConfig, ChatResult};
use mlx_core::models::nemotron_h::model::NemotronHModel;
use mlx_core::tokenizer::ChatMessage;

/// Clone the checkpoint into a tempdir with `config.json` patched to pin the
/// paged flag.
fn clone_model_dir(src: &Path, suffix: &str, use_block_paged: bool) -> Result<PathBuf, String> {
    let pid = std::process::id();
    let workspace_target = std::env::var_os("CARGO_TARGET_DIR")
        .map(PathBuf::from)
        .unwrap_or_else(|| {
            let manifest = std::env::var("CARGO_MANIFEST_DIR")
                .expect("CARGO_MANIFEST_DIR must be set when running cargo test");
            let mut p = PathBuf::from(manifest);
            p.pop();
            p.pop();
            p.join("target")
        });

    let dst = workspace_target.join(format!("nemotron-parity-{pid}-{suffix}"));
    if dst.exists() {
        let _ = fs::remove_dir_all(&dst);
    }
    fs::create_dir_all(&dst).map_err(|e| format!("create_dir_all({}): {e}", dst.display()))?;

    let read_dir = fs::read_dir(src).map_err(|e| format!("read_dir({}): {e}", src.display()))?;
    for entry in read_dir {
        let entry = entry.map_err(|e| format!("dir entry: {e}"))?;
        let from = entry.path();
        let to = dst.join(entry.file_name());
        if from.is_file() {
            let name = entry.file_name();
            if name == "config.json" {
                fs::copy(&from, &to)
                    .map_err(|e| format!("copy({} -> {}): {e}", from.display(), to.display()))?;
            } else {
                std::os::unix::fs::symlink(&from, &to)
                    .map_err(|e| format!("symlink({} -> {}): {e}", from.display(), to.display()))?;
            }
        }
    }

    // Pin explicitly in BOTH branches: otherwise the flat clone default-ons and
    // this compares paged against paged.
    let cfg_path = dst.join("config.json");
    let raw = fs::read_to_string(&cfg_path)
        .map_err(|e| format!("read config.json: {e} (path={})", cfg_path.display()))?;
    let mut cfg: serde_json::Value = serde_json::from_str(&raw)
        .map_err(|e| format!("parse config.json: {e} (path={})", cfg_path.display()))?;
    cfg["use_block_paged_cache"] = serde_json::Value::Bool(use_block_paged);
    if use_block_paged {
        cfg["paged_cache_memory_mb"] = serde_json::Value::from(512u32);
        cfg["paged_block_size"] = serde_json::Value::from(16u32);
    }
    let pretty =
        serde_json::to_string_pretty(&cfg).map_err(|e| format!("serialize config.json: {e}"))?;
    fs::write(&cfg_path, pretty).map_err(|e| format!("write config.json: {e}"))?;

    Ok(dst)
}

fn parity_chat_config(max_new_tokens: i32) -> ChatConfig {
    ChatConfig {
        cache_salt: None,
        cache_owner_id: Some("parity".to_string()),
        cache_root_owner_id: Some("parity".to_string()),
        max_new_tokens: Some(max_new_tokens),
        temperature: Some(0.0),
        repetition_penalty: Some(1.0),
        presence_penalty: Some(0.0),
        frequency_penalty: Some(0.0),
        max_consecutive_tokens: Some(0),
        max_ngram_repeats: Some(0),
        ngram_size: Some(0),
        enable_mtp: Some(false),
        include_reasoning: Some(true),
        report_performance: Some(false),
        reuse_cache: Some(true),
        ..ChatConfig::default()
    }
}

fn user_message(content: &str) -> ChatMessage {
    ChatMessage {
        role: "user".to_string(),
        content: content.to_string(),
        tool_calls: None,
        tool_call_id: None,
        is_error: None,
        reasoning_content: None,
        thinking_enabled: None,
        images: None,
        audio: None,
    }
}

fn assistant_message(result: &ChatResult) -> ChatMessage {
    ChatMessage {
        role: "assistant".to_string(),
        // Exact generated bytes, so the next full-history render strictly
        // extends the live cache.
        content: result.raw_text.clone(),
        tool_calls: None,
        tool_call_id: None,
        is_error: None,
        reasoning_content: None,
        thinking_enabled: Some(result.thinking_enabled),
        images: None,
        audio: None,
    }
}

fn resolve_source_model() -> Option<PathBuf> {
    let Ok(model_path) = std::env::var("MLX_TEST_MODEL_PATH") else {
        eprintln!("skipping: MLX_TEST_MODEL_PATH unset");
        return None;
    };
    let p = PathBuf::from(&model_path);
    if !p.exists() {
        eprintln!(
            "skipping: MLX_TEST_MODEL_PATH does not exist: {}",
            p.display()
        );
        return None;
    }
    Some(p)
}

fn assert_same_text(expected: &ChatResult, actual: &ChatResult, label: &str) {
    if expected.text != actual.text {
        let first_diff = expected
            .text
            .as_bytes()
            .iter()
            .zip(actual.text.as_bytes().iter())
            .position(|(a, b)| a != b);
        panic!(
            "TEXT MISMATCH on {label}: first_diff_byte={first_diff:?}\nFLAT  text={:?}\nPAGED text={:?}",
            expected.text, actual.text
        );
    }
    assert_eq!(
        expected.num_tokens, actual.num_tokens,
        "num_tokens mismatch on {label}: flat={} paged={}",
        expected.num_tokens, actual.num_tokens
    );
    assert_eq!(
        expected.finish_reason, actual.finish_reason,
        "finish_reason mismatch on {label}"
    );
}

#[tokio::test(flavor = "multi_thread", worker_threads = 4)]
#[ignore = "needs MLX_TEST_MODEL_PATH pointing to a real NemotronH checkpoint"]
async fn nemotron_h_paged_vs_flat_greedy_parity() {
    let Some(src) = resolve_source_model() else {
        return;
    };

    let flat_dir = clone_model_dir(&src, "nemotron-flat", false).expect("clone flat");
    let paged_dir = clone_model_dir(&src, "nemotron-paged", true).expect("clone paged");
    let flat_model = NemotronHModel::load(flat_dir.to_string_lossy().into_owned())
        .await
        .expect("load flat NemotronH");
    let paged_model = NemotronHModel::load(paged_dir.to_string_lossy().into_owned())
        .await
        .expect("load paged NemotronH");
    assert!(
        !flat_model.has_block_paged_cache(),
        "flat clone must be flat"
    );
    assert!(
        paged_model.has_block_paged_cache(),
        "paged clone must be paged"
    );

    let prompts = [
        "Say hi in one short word.",
        "What is 2 + 3? Answer with just the number.",
        "Name a primary color.",
    ];
    for (idx, prompt) in prompts.iter().enumerate() {
        let r_flat = flat_model
            .chat_session_start(vec![user_message(prompt)], Some(parity_chat_config(24)))
            .await
            .unwrap_or_else(|e| panic!("flat chat_session_start failed (prompt #{idx}): {e:?}"));
        let r_paged = paged_model
            .chat_session_start(vec![user_message(prompt)], Some(parity_chat_config(24)))
            .await
            .unwrap_or_else(|e| panic!("paged chat_session_start failed (prompt #{idx}): {e:?}"));
        assert_same_text(&r_flat, &r_paged, &format!("prompt #{idx} ({prompt:?})"));
    }
    eprintln!(
        "NemotronH greedy parity: all {} prompts matched",
        prompts.len()
    );
}

/// Two-turn dialog parity: the paged cross-turn prefix/keep-live path against
/// the flat warm-continue path.
#[tokio::test(flavor = "multi_thread", worker_threads = 4)]
#[ignore = "needs MLX_TEST_MODEL_PATH pointing to a real NemotronH checkpoint"]
async fn nemotron_h_paged_vs_flat_two_turn_dialog_parity() {
    let Some(src) = resolve_source_model() else {
        return;
    };

    let flat_dir = clone_model_dir(&src, "nemotron-flat-dialog", false).expect("clone flat");
    let paged_dir = clone_model_dir(&src, "nemotron-paged-dialog", true).expect("clone paged");
    let flat_model = NemotronHModel::load(flat_dir.to_string_lossy().into_owned())
        .await
        .expect("load flat NemotronH");
    let paged_model = NemotronHModel::load(paged_dir.to_string_lossy().into_owned())
        .await
        .expect("load paged NemotronH");

    let turn1 = "Tell me a very short story about a fox.";
    let turn2 = "What color was the fox? Answer in one word.";

    let r1_flat = flat_model
        .chat_session_start(vec![user_message(turn1)], Some(parity_chat_config(24)))
        .await
        .expect("flat turn 1");
    let r1_paged = paged_model
        .chat_session_start(vec![user_message(turn1)], Some(parity_chat_config(24)))
        .await
        .expect("paged turn 1");
    assert_same_text(&r1_flat, &r1_paged, "dialog turn 1");

    let history_flat = vec![
        user_message(turn1),
        assistant_message(&r1_flat),
        user_message(turn2),
    ];
    let history_paged = vec![
        user_message(turn1),
        assistant_message(&r1_paged),
        user_message(turn2),
    ];
    let r2_flat = flat_model
        .chat_session_start(history_flat, Some(parity_chat_config(24)))
        .await
        .expect("flat turn 2");
    let r2_paged = paged_model
        .chat_session_start(history_paged, Some(parity_chat_config(24)))
        .await
        .expect("paged turn 2");
    assert_same_text(&r2_flat, &r2_paged, "dialog turn 2");
    eprintln!("NemotronH two-turn dialog parity matched");
}
