/**
 * Speculative Decoding for Qwen3 Models
 *
 * Implements speculative decoding (assisted generation) where a smaller draft model
 * generates tokens speculatively, and a larger target model verifies them in a single
 * forward pass. This can achieve 2-3x speedup when the draft model has high acceptance rate.
 *
 * Reference: https://arxiv.org/abs/2211.17192 (Speculative Decoding)
 * Reference: mlx-lm/mlx_lm/generate.py (speculative_generate_step)
 *
 * ## Algorithm Overview
 *
 * 1. Draft model generates N tokens speculatively (fast, cheap forward passes)
 * 2. Target model verifies all N tokens in one forward pass (expensive but batched)
 * 3. Accept/reject using rejection sampling:
 *    - Accept if target agrees or is more confident
 *    - Reject: resample from adjusted distribution, discard remaining drafts
 * 4. Rewind caches when rejection occurs
 *
 * ## Acceptance Criterion
 *
 * For each draft token, accept with probability:
 *   min(1, target_prob / draft_prob)
 *
 * When rejecting, sample from adjusted distribution:
 *   adjusted = max(0, target_prob - draft_prob)
 *   adjusted = adjusted / sum(adjusted)
 */
use crate::array::MxArray;
use crate::nn::Activations;
// Note: SamplingConfig and sample are used elsewhere in the crate, but verify_draft_tokens
// uses its own probability-based sampling via MxArray::categorical
use napi::bindgen_prelude::*;
use tracing::debug;

/// Statistics from speculative decoding
#[derive(Debug, Clone, Default)]
pub struct SpeculativeStats {
    /// Total number of draft tokens proposed
    pub total_drafted: usize,
    /// Number of draft tokens accepted
    pub total_accepted: usize,
    /// Number of target forward passes
    pub target_forward_passes: usize,
    /// Number of draft forward passes
    pub draft_forward_passes: usize,
}

impl SpeculativeStats {
    /// Calculate the acceptance rate
    pub fn acceptance_rate(&self) -> f64 {
        if self.total_drafted == 0 {
            0.0
        } else {
            self.total_accepted as f64 / self.total_drafted as f64
        }
    }

    /// Calculate the average tokens generated per target forward pass
    pub fn tokens_per_target_pass(&self) -> f64 {
        if self.target_forward_passes == 0 {
            0.0
        } else {
            (self.total_accepted + self.target_forward_passes) as f64
                / self.target_forward_passes as f64
        }
    }
}

/// Result of verifying draft tokens against target model
pub struct VerificationResult {
    /// Number of accepted tokens (0 to num_draft)
    pub num_accepted: usize,
    /// The accepted tokens
    pub accepted_tokens: Vec<u32>,
    /// Log probabilities for accepted tokens
    pub accepted_logprobs: Vec<f32>,
    /// The final token (either last accepted or resampled)
    pub final_token: u32,
    /// Log probability of the final token
    pub final_logprob: f32,
    /// Whether generation should stop (EOS encountered)
    pub should_stop: bool,
}

/// Verify draft tokens against target model logits using rejection sampling.
///
/// This implements the acceptance/rejection criterion from speculative decoding:
/// - Accept draft token with probability min(1, target_p / draft_p)
/// - On rejection, resample from adjusted distribution max(0, target - draft)
///
/// # Arguments
/// * `draft_tokens` - Tokens generated by draft model
/// * `draft_probs` - Probabilities for each draft token (from draft model)
/// * `target_logits` - Logits from target model for all positions [num_draft+1, vocab_size]
/// * `temperature` - Sampling temperature
/// * `eos_token_id` - EOS token ID for stopping
///
/// # Returns
/// VerificationResult with accepted tokens and final state
pub fn verify_draft_tokens(
    draft_tokens: &[u32],
    draft_probs: &[MxArray],
    target_logits: &MxArray,
    temperature: f64,
    eos_token_id: Option<i32>,
) -> Result<VerificationResult> {
    let num_draft = draft_tokens.len();
    let mut accepted_tokens = Vec::with_capacity(num_draft);
    let mut accepted_logprobs = Vec::with_capacity(num_draft);
    let mut num_accepted = 0usize;
    let mut should_stop = false;

    // Apply temperature and compute target probabilities
    let scaled_logits = if temperature != 1.0 && temperature > 0.0 {
        target_logits.div_scalar(temperature)?
    } else {
        target_logits.clone()
    };

    // Get vocab size
    let vocab_size = scaled_logits.shape_at(1)? as usize;

    // Convert target logits to probabilities
    let target_probs = Activations::softmax(&scaled_logits, Some(-1))?;
    target_probs.eval();
    let target_probs_data = target_probs.to_float32()?;

    // Also compute log probabilities for logprob tracking
    let target_logprobs = Activations::log_softmax(&scaled_logits, Some(-1))?;
    target_logprobs.eval();
    let target_logprobs_data = target_logprobs.to_float32()?;

    // Process each draft token
    for i in 0..num_draft {
        let draft_token = draft_tokens[i];

        // Get draft probability for this token
        draft_probs[i].eval();
        let draft_p_data = draft_probs[i].to_float32()?;
        let draft_p = draft_p_data[draft_token as usize];

        // Get target probability for this token (position i in target_logits)
        let target_p = target_probs_data[i * vocab_size + draft_token as usize];

        // Acceptance criterion: accept with probability min(1, target_p / draft_p)
        // Using uniform random number for rejection sampling
        let r: f32 = rand::random();
        let accept_prob = if draft_p > 0.0 {
            (target_p / draft_p).min(1.0)
        } else {
            // If draft had zero probability but target has some, always accept
            if target_p > 0.0 { 1.0 } else { 0.0 }
        };

        if r < accept_prob {
            // Accept this token
            accepted_tokens.push(draft_token);
            let logprob = target_logprobs_data[i * vocab_size + draft_token as usize];
            accepted_logprobs.push(logprob);
            num_accepted += 1;

            // Check for EOS
            if let Some(eos_id) = eos_token_id
                && draft_token == eos_id as u32
            {
                should_stop = true;
                break;
            }
        } else {
            // Reject - resample from adjusted distribution
            // adjusted = max(0, target - draft) normalized
            let target_slice = &target_probs_data[i * vocab_size..(i + 1) * vocab_size];

            let mut adjusted = vec![0.0f32; vocab_size];
            let mut sum = 0.0f32;

            for (j, &t_p) in target_slice.iter().enumerate() {
                let d_p = draft_p_data.get(j).copied().unwrap_or(0.0);
                let adj = (t_p - d_p).max(0.0);
                adjusted[j] = adj;
                sum += adj;
            }

            // Normalize
            if sum > 0.0 {
                for p in adjusted.iter_mut() {
                    *p /= sum;
                }
            }

            // Sample from adjusted distribution
            let adjusted_arr = MxArray::from_float32(&adjusted, &[vocab_size as i64])?;
            let resampled = adjusted_arr.categorical(Some(-1))?;
            resampled.eval();
            let new_token = resampled.item_at_int32(0)? as u32;

            // Add the resampled token to output (but don't count as "accepted")
            accepted_tokens.push(new_token);
            let logprob = target_logprobs_data[i * vocab_size + new_token as usize];
            accepted_logprobs.push(logprob);
            // DO NOT increment num_accepted here - this is a resampled token, not an accepted draft

            // Check for EOS
            if let Some(eos_id) = eos_token_id
                && new_token == eos_id as u32
            {
                should_stop = true;
            }

            // Don't process remaining draft tokens
            break;
        }
    }

    // If all drafts were accepted, we need to sample one more token from the last position
    let (final_token, final_logprob) = if num_accepted == num_draft && !should_stop {
        // Sample from position num_draft (the "bonus" token from target model)
        let last_target_probs = &target_probs_data[num_draft * vocab_size..];
        let last_arr = MxArray::from_float32(last_target_probs, &[vocab_size as i64])?;
        let sampled = last_arr.categorical(Some(-1))?;
        sampled.eval();
        let token = sampled.item_at_int32(0)? as u32;
        let logprob = target_logprobs_data[num_draft * vocab_size + token as usize];

        accepted_tokens.push(token);
        accepted_logprobs.push(logprob);

        // Check for EOS
        if let Some(eos_id) = eos_token_id
            && token == eos_id as u32
        {
            should_stop = true;
        }

        (token, logprob)
    } else if !accepted_tokens.is_empty() {
        let token = *accepted_tokens.last().unwrap();
        let logprob = *accepted_logprobs.last().unwrap();
        (token, logprob)
    } else {
        // Edge case: no tokens accepted at all (shouldn't happen normally)
        // Sample from first position
        let first_target_probs = &target_probs_data[..vocab_size];
        let first_arr = MxArray::from_float32(first_target_probs, &[vocab_size as i64])?;
        let sampled = first_arr.categorical(Some(-1))?;
        sampled.eval();
        let token = sampled.item_at_int32(0)? as u32;
        let logprob = target_logprobs_data[token as usize];

        accepted_tokens.push(token);
        accepted_logprobs.push(logprob);

        if let Some(eos_id) = eos_token_id
            && token == eos_id as u32
        {
            should_stop = true;
        }

        (token, logprob)
    };

    Ok(VerificationResult {
        num_accepted, // Use the variable, not accepted_tokens.len()
        accepted_tokens,
        accepted_logprobs,
        final_token,
        final_logprob,
        should_stop,
    })
}

/// Trim multiple KV caches to a specific length.
///
/// Used after rejection to rewind caches to the last accepted position.
pub fn trim_kv_caches(
    kv_keys: &mut [Option<MxArray>],
    _kv_values: &mut [Option<MxArray>],
    cache_idx: &mut i32,
    new_len: i32,
) {
    // The cache arrays are managed by forward_fused which uses cache_idx
    // to track the current position. We just need to update cache_idx.
    // The next forward pass will overwrite the trimmed portion.
    *cache_idx = new_len;

    debug!(
        "Trimmed KV caches: {} layers, new cache_idx={}",
        kv_keys.len(),
        new_len
    );
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_speculative_stats() {
        let stats = SpeculativeStats {
            total_drafted: 100,
            total_accepted: 80,
            target_forward_passes: 25,
            draft_forward_passes: 100,
        };

        assert!((stats.acceptance_rate() - 0.8).abs() < 0.001);
        // (80 accepted + 25 resampled) / 25 passes = 4.2 tokens per pass
        assert!((stats.tokens_per_target_pass() - 4.2).abs() < 0.001);
    }

    #[test]
    fn test_speculative_stats_empty() {
        let stats = SpeculativeStats::default();
        assert_eq!(stats.acceptance_rate(), 0.0);
        assert_eq!(stats.tokens_per_target_pass(), 0.0);
    }

    #[test]
    fn test_verify_draft_tokens_all_accept() {
        // Create simple draft and target distributions that should lead to acceptance
        // Draft and target have same distribution -> 100% acceptance rate
        let draft_tokens = vec![1u32, 2, 3];

        // Create uniform-ish probabilities
        let mut probs = vec![0.1f32; 10];
        probs[1] = 0.3;
        probs[2] = 0.3;
        probs[3] = 0.3;

        let draft_probs: Vec<MxArray> = (0..3)
            .map(|_| MxArray::from_float32(&probs, &[10]).unwrap())
            .collect();

        // Target logits: 4 positions (3 draft + 1 bonus), vocab_size=10
        // Create logits that will produce similar probabilities
        let mut logits = vec![0.0f32; 40];
        for i in 0..4 {
            logits[i * 10 + 1] = 1.0;
            logits[i * 10 + 2] = 1.0;
            logits[i * 10 + 3] = 1.0;
        }
        let target_logits = MxArray::from_float32(&logits, &[4, 10]).unwrap();

        let result = verify_draft_tokens(&draft_tokens, &draft_probs, &target_logits, 1.0, None);
        assert!(result.is_ok());

        let result = result.unwrap();
        // With similar distributions, most should be accepted
        // num_accepted counts only draft tokens that passed acceptance test
        // accepted_tokens includes accepted drafts + possibly a resampled token + possibly a bonus token
        assert!(result.num_accepted <= draft_tokens.len());
        assert!(!result.accepted_tokens.is_empty());
        // accepted_tokens should always have at least as many tokens as num_accepted
        assert!(result.accepted_tokens.len() >= result.num_accepted);
    }

    #[test]
    fn test_verify_draft_tokens_with_eos() {
        // Test that EOS detection works
        let draft_tokens = vec![1u32, 2, 99]; // 99 is EOS

        let mut probs = vec![0.01f32; 100];
        probs[1] = 0.3;
        probs[2] = 0.3;
        probs[99] = 0.3;

        let draft_probs: Vec<MxArray> = (0..3)
            .map(|_| MxArray::from_float32(&probs, &[100]).unwrap())
            .collect();

        let mut logits = vec![0.0f32; 400];
        for i in 0..4 {
            logits[i * 100 + 1] = 1.0;
            logits[i * 100 + 2] = 1.0;
            logits[i * 100 + 99] = 1.0;
        }
        let target_logits = MxArray::from_float32(&logits, &[4, 100]).unwrap();

        let result =
            verify_draft_tokens(&draft_tokens, &draft_probs, &target_logits, 1.0, Some(99));
        assert!(result.is_ok());

        // The result should indicate stop was encountered (either via acceptance or resampling)
        // This is probabilistic, but the test verifies the code path works
        let result = result.unwrap();
        // num_accepted counts only draft tokens that passed acceptance test (0 to num_draft)
        // accepted_tokens always has at least one token (either accepted or resampled)
        assert!(result.num_accepted <= draft_tokens.len());
        assert!(!result.accepted_tokens.is_empty());
    }
}
