import * as React from 'react';

import { useLocale } from '../../lib/i18n-react';

/**
 * Chapter 15 (post-training) sub-chapter "Knowledge distillation" — a
 * side-by-side comparison of the two eras of LLM distillation, sharing one
 * frame: a TEACHER model's output becomes the STUDENT's training target,
 * instead of (or alongside) a human-written one.
 *
 * LEFT — classic distillation (Hinton, Vinyals & Dean, arXiv:1503.02531,
 * 2015): soften the teacher's softmax with a temperature T, train the student
 * to match that same softened distribution. The bar chart is a LIVE
 * recomputation of softmax(z/T) over four illustrative classes so a reader can
 * drag T and watch "dark knowledge" — the relative probability of the WRONG
 * answers — spread out. The four classes and the quote are the paper's own
 * running example (Section 1, quoted verbatim in the caption); the logits
 * themselves are invented for illustration (the paper never publishes them),
 * which the footnote says outright.
 *
 * RIGHT — modern response-based distillation (DeepSeek-R1, arXiv:2501.12948,
 * Appendix F): no soft distribution, no KL — just ordinary SFT next-token
 * cross-entropy where the "label" is the teacher's own generated response
 * text. The bar pair reproduces the paper's own Appendix F.1 number: distilling
 * DeepSeek-R1 into Qwen2.5-32B (SFT only, no RL) reaches AIME 2024 pass@1
 * 72.6, versus 47.0 for RL-training that same base model directly with no
 * distillation ("Qwen2.5-32B-Zero").
 *
 * Both panels are pure SVG/HTML + React, no model/worker dependency — SSR-safe.
 */

// Four illustrative classes for the temperature-softening demo, in the order
// the paper's own example lists them: correct answer, near-miss, far-miss,
// far-miss. Logits are invented (chosen only to make the effect legible across
// T = 1..20) — the paper describes the effect qualitatively and publishes no
// logit values for this particular example.
const DEMO_LOGITS = [60, 25, 3, -3] as const;
const T_MIN = 1;
const T_MAX = 20;
const T_DEFAULT = 6;

const COPY = {
  en: {
    header: 'Two eras of distillation, same teacher → student idea',
    intro:
      'Both trainings below fine-tune a small STUDENT model on a big TEACHER model’s output instead of (or in addition to) a human-written label. What differs is what counts as the "label."',
    // Left panel — classic Hinton distillation
    leftTag: 'Classic · Hinton, Vinyals & Dean, 2015',
    leftTitle: 'Soft targets at a shared temperature',
    leftBody:
      'Soften the teacher’s softmax with a temperature T, then train the student to match that SAME softened distribution at that SAME T (plus a lighter cross-entropy on the true hard label at T = 1). Drag T and watch the wrong-answer probabilities grow from vanishing to visible:',
    tSlider: 'Temperature T',
    classNames: ['BMW (correct)', 'garbage truck', 'carrot', 'sofa'],
    quote:
      '“An image of a BMW, for example, may only have a very small chance of being mistaken for a garbage truck, but that mistake is still many times more probable than mistaking it for a carrot.”',
    quoteCite: '— Hinton, Vinyals & Dean, “Distilling the Knowledge in a Neural Network,” arXiv:1503.02531, §1',
    leftFootnote:
      'Logits (60, 25, 3, −3) are invented for illustration — the paper describes this example qualitatively and publishes no logit values for it. At T = 1 the distribution is nearly one-hot on BMW, and the wrong answers are pinned near zero — too small to carry a learnable signal. Raising T inflates them to a visible, comparable size, exposing the relative structure among them — the "dark knowledge" the student also learns to imitate — even as the softening pulls every probability, right answer included, toward the uniform distribution. Because the soft-target gradient scales as 1/T², Hinton’s loss multiplies that term by T² so its weight stays constant as T changes.',
    // Right panel — modern response-based distillation
    rightTag: 'Modern · DeepSeek-R1-Distill, 2025',
    rightTitle: 'Plain SFT on teacher-written text',
    rightBody:
      'No soft distribution, no KL divergence at all — just ordinary next-token cross-entropy, the same loss the training chapter introduced, on (prompt, response) pairs where the RESPONSE was generated by the teacher instead of a human annotator.',
    samplePrompt: 'Prompt: "Prove that √2 is irrational."',
    sampleResponse: 'DeepSeek-R1’s response → SFT target for the student:',
    sampleThink: '<think> Assume, for contradiction, that √2 = p/q in lowest terms… </think>',
    sampleAnswer: 'So √2 cannot be rational. ∎',
    sampleCaption: 'Every one of these tokens gets an ordinary −log p(token) loss — exactly like SFT, just with a bigger, smarter source of training text.',
    aimeTitle: 'AIME 2024 pass@1: distillation vs. direct RL, same size',
    aimeBar1Label: 'Qwen2.5-32B-Zero',
    aimeBar1Sub: 'direct RL, no distillation',
    aimeBar2Label: 'DeepSeek-R1-Distill-Qwen-32B',
    aimeBar2Sub: 'SFT-distilled from R1, no RL stage',
    aimeCite: 'DeepSeek-R1 paper, Appendix F.1 (arXiv:2501.12948): “we apply only SFT and do not include an RL stage” for the distilled models.',
    footer:
      'Both are called "distillation" for the same reason — a smaller student learns from a bigger teacher instead of only from humans. What changes across the two eras is exactly one thing: whether the target is a temperature-softened probability distribution, or the teacher’s own generated text treated as an ordinary SFT example.',
  },
  zh: {
    header: '两个时代的蒸馏，同一个 teacher → student 思路',
    intro:
      '下面两种训练都是在一个小的 STUDENT 模型上做微调，用大 TEACHER 模型的输出作为标签，来替代（或补充）人工写的标签。两者的差别只在于什么算「标签」。',
    leftTag: '经典 · Hinton, Vinyals & Dean, 2015',
    leftTitle: '在共享温度下的软标签',
    leftBody:
      '用温度 T 软化 teacher 的 softmax，再训练 student 在同一个 T 下去匹配这个同样软化过的分布（再加上一个较轻的、在 T = 1 时对真实硬标签的交叉熵）。拖动 T，看错误答案的概率如何从几乎为零变得清晰可见：',
    tSlider: '温度 T',
    classNames: ['宝马（正确答案）', '垃圾车', '胡萝卜', '沙发'],
    quote:
      '「例如一张宝马汽车的图片，被误认成垃圾车的概率或许非常小，但这个概率仍然比被误认成胡萝卜的概率要高出许多倍。」',
    quoteCite: '——Hinton, Vinyals & Dean，《Distilling the Knowledge in a Neural Network》，arXiv:1503.02531，第 1 节',
    leftFootnote:
      '这里的 logits（60、25、3、−3）是为了演示效果而虚构的——论文只是定性描述了这个例子，并未公布具体的 logit 数值。T = 1 时分布几乎是宝马的 one-hot，错误答案的概率都被压得接近零——小到无法携带可学习的信号。调高 T 会把它们撑大到一个清晰、可比较的量级，暴露出它们之间的相对结构——这正是 student 也会一并学到的「暗知识」——即便同时软化也在把每一个概率（包括正确答案）都拉向均匀分布。因为软标签项的梯度按 1/T² 缩放，Hinton 的损失把这一项乘以 T²，让它的权重不随 T 变化而改变。',
    rightTag: '现代 · DeepSeek-R1-Distill，2025',
    rightTitle: '直接对 teacher 写的文本做 SFT',
    rightBody:
      '完全没有软分布，也没有 KL 散度——就是普通的下一个 token 交叉熵，跟 training 那一章讲的损失一模一样，只是 (prompt, response) 里的 RESPONSE 换成了由 teacher 生成、而不是人工标注。',
    samplePrompt: 'Prompt：「证明 √2 是无理数。」',
    sampleResponse: 'DeepSeek-R1 的回复 → student 的 SFT 目标：',
    sampleThink: '<think> 反证法：假设 √2 = p/q 且已约分到最简… </think>',
    sampleAnswer: '所以 √2 不可能是有理数。∎',
    sampleCaption: '这里的每一个 token 都会算一个普通的 −log p(token) 损失——跟 SFT 完全一样，只是训练文本换了个更大、更聪明的来源。',
    aimeTitle: 'AIME 2024 pass@1：蒸馏 vs. 直接 RL，同等规模',
    aimeBar1Label: 'Qwen2.5-32B-Zero',
    aimeBar1Sub: '直接 RL，不蒸馏',
    aimeBar2Label: 'DeepSeek-R1-Distill-Qwen-32B',
    aimeBar2Sub: '从 R1 蒸馏而来（SFT），无 RL 阶段',
    aimeCite: 'DeepSeek-R1 论文附录 F.1（arXiv:2501.12948）：对蒸馏模型「我们只应用 SFT，不包含 RL 阶段」。',
    footer:
      '两者都被称为「蒸馏」，原因相同——一个更小的 student 向一个更大的 teacher 学习，而不只是向人类学习。两个时代真正不同的只有一件事：目标究竟是一个被温度软化过的概率分布，还是 teacher 自己生成的、被当成普通 SFT 样本对待的文本。',
  },
} as const;

function softmaxAtT(logits: readonly number[], t: number): number[] {
  const scaled = logits.map((z) => z / t);
  const m = Math.max(...scaled);
  const exps = scaled.map((s) => Math.exp(s - m));
  const sum = exps.reduce((a, b) => a + b, 0);
  return exps.map((e) => e / sum);
}

function TempBars({ probs, names }: { probs: number[]; names: readonly string[] }) {
  return (
    <div className="space-y-1 rounded-md border border-border/60 bg-muted/10 p-2">
      {names.map((name, i) => {
        const pct = probs[i]! * 100;
        const isTarget = i === 0;
        return (
          <div key={name} className="grid grid-cols-[7rem_minmax(0,1fr)_3.4rem] items-center gap-2 text-[11px]">
            <span className={['truncate', isTarget ? 'font-semibold text-primary' : 'text-foreground/80'].join(' ')}>
              {name}
            </span>
            <div className="relative h-3.5 w-full overflow-hidden rounded bg-muted">
              <div
                className={['h-full transition-[width] duration-150', isTarget ? 'bg-primary' : 'bg-foreground/40'].join(
                  ' ',
                )}
                style={{ width: `${Math.max(0.4, Math.min(100, pct))}%` }}
              />
            </div>
            <span className="text-right font-mono text-muted-foreground">
              {pct >= 1 ? pct.toFixed(1) : pct.toFixed(3)}%
            </span>
          </div>
        );
      })}
    </div>
  );
}

function AimeBars({
  bar1Label,
  bar1Sub,
  bar2Label,
  bar2Sub,
}: {
  bar1Label: string;
  bar1Sub: string;
  bar2Label: string;
  bar2Sub: string;
}) {
  const rows = [
    { label: bar1Label, sub: bar1Sub, value: 47.0, accent: false },
    { label: bar2Label, sub: bar2Sub, value: 72.6, accent: true },
  ];
  const max = 100;
  return (
    <div className="space-y-2 rounded-md border border-border/60 bg-muted/10 p-2">
      {rows.map((r) => (
        <div key={r.label} className="space-y-0.5">
          <div className="flex items-baseline justify-between gap-2 text-[11px]">
            <span className={r.accent ? 'font-semibold text-primary' : 'text-foreground/80'}>{r.label}</span>
            <span className="font-mono text-muted-foreground">{r.value.toFixed(1)}</span>
          </div>
          <div className="relative h-3.5 w-full overflow-hidden rounded bg-muted">
            <div
              className={['h-full', r.accent ? 'bg-primary' : 'bg-foreground/40'].join(' ')}
              style={{ width: `${(r.value / max) * 100}%` }}
            />
          </div>
          <div className="text-[10px] text-muted-foreground">{r.sub}</div>
        </div>
      ))}
    </div>
  );
}

export function DistillationPipelines() {
  const copy = COPY[useLocale()];
  const [temperature, setTemperature] = React.useState(T_DEFAULT);
  const probs = React.useMemo(() => softmaxAtT(DEMO_LOGITS, temperature), [temperature]);

  return (
    <div className="not-prose my-5 space-y-4 rounded-md border border-border bg-background p-3">
      <div className="text-xs uppercase tracking-wider text-muted-foreground">{copy.header}</div>
      <p className="text-[12px] text-foreground/85">{copy.intro}</p>

      <div className="grid gap-4 md:grid-cols-2">
        {/* LEFT — classic Hinton soft-target distillation */}
        <div className="flex min-w-0 flex-col gap-2 rounded-md border border-border/60 p-2.5">
          <div className="flex items-baseline justify-between gap-2">
            <span className="font-mono text-[10px] uppercase tracking-wider text-muted-foreground">
              {copy.leftTag}
            </span>
          </div>
          <div className="text-[13px] font-medium text-foreground">{copy.leftTitle}</div>
          <p className="text-[11px] text-foreground/85">{copy.leftBody}</p>

          <label className="block text-[11px]">
            <div className="mb-0.5 flex justify-between font-mono text-muted-foreground">
              <span>{copy.tSlider}</span>
              <span>{`T = ${temperature}`}</span>
            </div>
            <input
              type="range"
              min={T_MIN}
              max={T_MAX}
              step={1}
              value={temperature}
              onChange={(e) => setTemperature(Number(e.target.value))}
              className="w-full"
            />
          </label>

          <TempBars probs={probs} names={copy.classNames} />

          <p className="text-[11px] italic text-foreground/80">{copy.quote}</p>
          <p className="text-[10px] text-muted-foreground">{copy.quoteCite}</p>
          <p className="text-[10px] text-muted-foreground">{copy.leftFootnote}</p>
        </div>

        {/* RIGHT — modern response-based SFT distillation */}
        <div className="flex min-w-0 flex-col gap-2 rounded-md border border-border/60 p-2.5">
          <div className="flex items-baseline justify-between gap-2">
            <span className="font-mono text-[10px] uppercase tracking-wider text-muted-foreground">
              {copy.rightTag}
            </span>
          </div>
          <div className="text-[13px] font-medium text-foreground">{copy.rightTitle}</div>
          <p className="text-[11px] text-foreground/85">{copy.rightBody}</p>

          <div className="space-y-1 rounded-md border border-border/60 bg-muted/10 p-2 font-mono text-[10.5px] leading-relaxed">
            <div className="text-muted-foreground">{copy.samplePrompt}</div>
            <div className="text-[10px] uppercase tracking-wider text-muted-foreground">{copy.sampleResponse}</div>
            <div className="text-foreground/70">{copy.sampleThink}</div>
            <div className="text-foreground/90">{copy.sampleAnswer}</div>
          </div>
          <p className="text-[10px] text-muted-foreground">{copy.sampleCaption}</p>

          <div className="pt-1 text-[11px] font-medium text-foreground">{copy.aimeTitle}</div>
          <AimeBars
            bar1Label={copy.aimeBar1Label}
            bar1Sub={copy.aimeBar1Sub}
            bar2Label={copy.aimeBar2Label}
            bar2Sub={copy.aimeBar2Sub}
          />
          <p className="text-[10px] text-muted-foreground">{copy.aimeCite}</p>
        </div>
      </div>

      <p className="text-[12px] text-foreground/85">{copy.footer}</p>
    </div>
  );
}
